### PR TITLE
IOExpander: add readAll() API

### PR DESCRIPTION
**Pull request by facchinm**
@manchoz

### CODE REVIEW

**Review by manchoz — APPROVED** [review]
LGTM

**Comment by Rocketct** [comment]
Hi guys did you check if the print of the pins is aligned with the headers number views? at last we decide to not include the writeAll?

**Comment by pnndra** [comment]
we need to also add the writeAll() API

**Comment by Rocketct** [comment]
ookk so let me check this if work correctly i'll merge and on top of this i'll push the writeAll()

**Review by Rocketct — APPROVED** [review]
this works fine i'm going to merge it and made the new PR for the write all

**Pull request merged**
