### PR TITLE
Analog input individual mode selection

### PR DESCRIPTION
**Pull request by SJThomas29**
Changed the analog_in.set... functions so they take a channel input. Allowing channel modes to be set individually. I.e. measure current on AI0 and voltage on AI1. Also updated analog in examples with this functionality with a link to warning in full-pinout documentation.

### CODE REVIEW

**Comment by facchinm** [comment]
@SJThomas29 thanks for the PR! I'd only add an overload for the function call without parameters so older sketches will not break (and examples will not need to be changed).
@Rocketct can you test the functionality in the meantime?

**Comment by SJThomas29** [comment]
> @SJThomas29 thanks for the PR! I'd only add an overload for the function call without parameters so older sketches will not break (and examples will not need to be changed). @Rocketct can you test the functionality in the meantime?

No problem! Good idea, that will work better. Have reverted the example changes and added the overload when no input is given.

**Comment by MDBInd** [comment]
Please can this PR be progressed. I really need this feature and the [documentation](https://docs.arduino.cc/resources/datasheets/AKX00032-datasheet.pdf) (Updated 08/05//2023) clearly states:

"Each channel is SW configurable to be:
0-10V input
4-20mA input
NTC input..."

I am happy to help in any way I can.
Many thanks

**Comment by AndrewDugenske** [comment]
Friends, A big vote for this PR to become finalized and added to the docs. Needing it for a project. Thanks for all you are doing!

**Comment by akash73** [comment]
@manchoz would you mind to give this a spin ?

**Comment by MDBInd** [comment]
As the CLA has not been signed would anyone object to me re-factoring @SJThomas29 code and creating a new PR?

**Comment by leonardocavagnis** [comment]
Hi @SJThomas29, 
Thank you for proposing this change. We've decided not to implement it.
The reason for this decision is our concern for hardware safety. Incorrect management could potentially damage the board.

**Comment by MDBInd** [comment]
@leonardocavagnis, This functionality is still cited in the data sheet dated 21/09/23 on Page 12:

"There are three independent analog input channels available. Each of them has an analog switch TS12A44514PWR
which is switching between three modes:
0-10V: The input is connected to a 100 kΩ and 39 kΩ resistor divider. A 0-10V input is scaled down to 0-2.8V.
The input impedance is approximately 28 kΩ.
4-20mA: The input is connected to a 120Ω resistor. Having 4-20mA current input for a 0.48V-2.4V voltage.
NTC: The input is connected to a 3V voltage reference (REF3330AIRSER) with a 100 kΩ resistor in series,
becoming part of a resistor divider powered by the voltage reference."

Are you going to update the documentation to align with your decision?

Please can you detail the potential damage you are sighting. I am using this PR in my code to monitor 0-10V and 4..20mA and have not experienced any problems for 4 months without issue.

**Pull request closed without merging**
