### PR TITLE
Library revamping

### LINKED ISSUE #50: RTC methods should be singolar
i.e setYear instead of setYears

### PR DESCRIPTION
**Pull request by leonardocavagnis**
- Library structure restyling
- Function and class names refactoring
- Removing unused functions
- Removing mbed core direct calls
- Reworking examples
- Adding documentation

### CODE REVIEW

**Comment by aliphys** [comment]
@leonardocavagnis If the compilation issues are to be fixed on release [4.0.6](https://github.com/arduino/ArduinoCore-mbed/releases/tag/4.0.6) of the core, this PR will be blocked until it is accessible for the `compile-sketches` workflow.

@Rocketct do we have any blockers for releasing 4.0.6?

**Comment by aliphys** [comment]
Commit https://github.com/arduino/ArduinoCore-mbed/commit/52caeac0926acbfb9a3f2b0fa3ba1c9996f103ec in 4.0.6 related to the compilation issues in this PR.

```
export LIBRARIES=("doom Ethernet MRI Portenta_SDRAM SPI WiFi ea_malloc openamp_arduino STM32H747_System ThreadDebug Himax_HM01B0 Himax_HM0360 PDM Arduino_H7_Video USBAudio KernelDebug Portenta_Audio RPC USBHID Wire Portenta_lvgl Camera rpclib USBHOST mbed-memory-status Portenta_SDCARD Scheduler USBMSD USBMIDI SocketWrapper GSM GPS MCUboot Arduino_CAN")
```

**Comment by aliphys** [comment]
[Arduino mbed core 4.0.6](https://github.com/arduino/ArduinoCore-mbed/releases/tag/4.0.6) is officially released (thanks @facchinm ) 🎉 

✅ Compiler checks all passing

**Review by mcmchris — CHANGES_REQUESTED** [review]
I've tested the Temp_Probes_Thermocouple example and it doesn't work with the new Library revamp. It works just fine with the published version of the library.

Error: it samples all three channels and outputs something near -2.0 C on each channel.

```
Temperature CH0 [°C]: -2.08
Temperature CH1 [°C]: -2.08
Temperature CH2 [°C]: -2.08
```

In the public library, it measures correctly where my TC is connected with an output for example like:
ch1: 30 C
ch2: nan
ch3: nan

I've tried to fix it playing with the enablement pins and stuff but nothing.

**Comment by leonardocavagnis** [comment]
Close PR due to deprecation

**Pull request closed without merging**
