### PR TITLE
Refactor RS485 support

### PR DESCRIPTION
**Pull request by manchoz**
Refactor the RS485 support to be compatible with the ArduinoRS485 library and ArduinoRS485-based tools and libraries (e.g. Arduino Modbus).

Please, review @facchinm @Rocketct

### CODE REVIEW

**Comment by manchoz** [comment]
Compile Examples CI is failing because this branch needs ArduinoRS485 from upstream (in particular of PR https://github.com/arduino-libraries/ArduinoRS485/pull/6)

**Comment by facchinm** [comment]
@manchoz should we release ArduinoRS485 and then merge this one?

**Comment by aentinger** [comment]
> @manchoz should we release ArduinoRS485 and then merge this one?

Up 🙃 👍

**Comment by manchoz** [comment]
@facchinm with the https://github.com/arduino-libraries/ArduinoRS485/pull/13 merged, [ArduinoRS485](https://github.com/arduino-libraries/ArduinoRS485) is ready to be released and this PR merged.

**Pull request merged**
